from __future__ import annotations

from vibe.core.team_workspace.git_transport import (
    GitSyncResult,
    GitTeamWorkspaceError,
    GitTeamWorkspaceTransport,
)
from vibe.core.team_workspace.identity import (
    derive_entry_id,
    derive_event_id,
    derive_run_id,
    discover_current_branch,
    discover_workspace_identity,
    new_client_id,
    normalize_project_remote,
    resolve_member_identity,
    resolve_team_repository_url,
)
from vibe.core.team_workspace.models import (
    ActivityState,
    ActivitySummary,
    ConnectionState,
    ConversationRole,
    HistoryScope,
    PresenceState,
    PrivacyMode,
    SyncError,
    TeamActivityEvent,
    TeamConversationEntry,
    TeamMemberPresence,
    TeamMemberSnapshot,
    TeamRunSnapshot,
    TeamWorkspaceIdentity,
    TeamWorkspaceManifest,
    TeamWorkspaceSnapshot,
)
from vibe.core.team_workspace.service import (
    LocalTeamClient,
    TeamWorkspaceListener,
    TeamWorkspaceService,
    build_team_workspace_service,
)

__all__ = [
    "ActivityState",
    "ActivitySummary",
    "ConnectionState",
    "ConversationRole",
    "GitSyncResult",
    "GitTeamWorkspaceError",
    "GitTeamWorkspaceTransport",
    "HistoryScope",
    "LocalTeamClient",
    "PresenceState",
    "PrivacyMode",
    "SyncError",
    "TeamActivityEvent",
    "TeamConversationEntry",
    "TeamMemberPresence",
    "TeamMemberSnapshot",
    "TeamRunSnapshot",
    "TeamWorkspaceIdentity",
    "TeamWorkspaceListener",
    "TeamWorkspaceManifest",
    "TeamWorkspaceService",
    "TeamWorkspaceSnapshot",
    "build_team_workspace_service",
    "derive_entry_id",
    "derive_event_id",
    "derive_run_id",
    "discover_current_branch",
    "discover_workspace_identity",
    "new_client_id",
    "normalize_project_remote",
    "resolve_member_identity",
    "resolve_team_repository_url",
]
